### ISSUE TITLE
太极-阴，无法使用

### ISSUE THREAD

**Issue by greenyi1984** [wuyuanyi135/XposedHuaweiVascularBypass#1]
太极-阴，无法使用。
截图如下。
![Screenshot_2021-04-05-19-52-14-59_8121ef2cc23a3edfdb1c2f4b9c942689](https://user-images.githubusercontent.com/33306964/113571591-40456200-9649-11eb-9a24-c48778c5fb27.jpg)

**Comment by wuyuanyi135** [comment]
我没有用过这款模块管理工具。请提供一下你的xposed版本信息

**Comment by wuyuanyi135** [comment]
https://taichi.cool/zh/doc/module-white-list.html

请参考这个文档的说明。

**Comment by greenyi1984** [comment]
> https://taichi.cool/zh/doc/module-white-list.html
> 
> 请参考这个文档的说明。

我看你之前的心脏健康bypass是在白名单的，这个新的心血管健康bypass能加进去嘛？

**Comment by wuyuanyi135** [comment]
@greenyi1984 这个白名单不是我申请的，可能是有其他用户提交过申请。你可以参照这个文档提交一下申请试试看。

**Comment by greenyi1984** [comment]
> @greenyi1984 这个白名单不是我申请的，可能是有其他用户提交过申请。你可以参照这个文档提交一下申请试试看。

我已经提交一个申请, 希望尽快通过.

**Comment by wuyuanyi135** [comment]
> > @greenyi1984 这个白名单不是我申请的，可能是有其他用户提交过申请。你可以参照这个文档提交一下申请试试看。
> 
> 我已经提交一个申请, 希望尽快通过.

@greenyi1984 多谢！

**Comment by wuyuanyi135** [comment]
@greenyi1984 Hi 如果你的审核已经通过请告知我并关闭一下这个issue. Thanks!

**Comment by wuyuanyi135** [comment]
Close for inactivity

**Comment by greenyi1984** [comment]
> Close for inactivity
有点尴尬，我那个申请一直没有人审核，发邮件也没有人回，可能是已经不维护了。

**Comment by wuyuanyi135** [comment]
@greenyi1984 试试别的Xposed管理器？
